# The prison's network policy, as an nftables ruleset in the store.
#
# Loaded by the HOST into the netns-owner container's namespace before
# anything joins it, exactly as nix/lan-ruleset.nix is. Nothing inside the
# prison reads, writes or can replace it, and the prison holds no capability
# to change what was loaded -- it is on the wrong side of the namespace
# boundary, which is the whole point of a separate namespace owner.
#
# Differs from lan-ruleset.nix in polarity: that one is default-accept with
# private ranges carved out, this one is default-drop with everything carved
# in. A prison that fails to load its ruleset is a prison with no network,
# not a prison with an open one.

{ pkgs
, lib ? pkgs.lib
, listen ? { tcp = [ ]; udp = [ ]; }
, egress ? { mode = "none"; targets = [ ]; lan = [ ]; }
}:

let
  inherit (lib) concatMapStringsSep concatStringsSep optionalString;

  set = xs: "{ " + concatStringsSep ", " (map toString xs) + " }";

  # Ranges that are, by definition, not the public internet. `mode =
  # "internet"` rejects these so that "may talk to the internet" cannot be
  # quietly read as "may talk to the machine next to it".
  privateV4 = [ "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "169.254.0.0/16" "100.64.0.0/10" ];
  privateV6 = [ "fc00::/7" "fe80::/10" ];

  isV6 = a: lib.hasInfix ":" a;

  # An egress target is one address and one port. Both are required: a rule
  # naming only a host would permit every service on it, which is the kind of
  # allowance that gets written once and never revisited.
  targetRule = t:
    let
      fam = if isV6 t.address then "ip6" else "ip";
      proto = t.protocol or "tcp";
    in
    "    ${fam} daddr ${t.address} ${proto} dport ${toString t.port} accept";

  listenRule = proto: p:
    if builtins.isInt p
    then "    ${proto} dport ${toString p} accept"
    else "    ${optionalString (p.address or null != null)
                 "${if isV6 p.address then "ip6" else "ip"} daddr ${p.address} "}${proto} dport ${toString p.port} accept";

  tcpListens = listen.tcp or [ ];
  udpListens = listen.udp or [ ];

  mode = egress.mode or "none";
  targets = egress.targets or [ ];
  lanAllow = egress.lan or [ ];

  lanV4 = lib.filter (a: !(isV6 a)) lanAllow;
  lanV6 = lib.filter isV6 lanAllow;

  egressBody =
    if mode == "none" then
      "    # egress.mode = \"none\": nothing leaves but loopback and replies."
    else if mode == "targets" then
      concatMapStringsSep "\n" targetRule targets
    else if mode == "internet" then
      concatMapStringsSep "\n" targetRule targets
      + optionalString (targets != [ ]) "\n"
      + optionalString (lanV4 != [ ]) "    ip daddr ${set lanV4} accept\n"
      + optionalString (lanV6 != [ ]) "    ip6 daddr ${set lanV6} accept\n"
      + ''
            # Everything that is not a private range. The drops come first so an
            # `accept` below cannot be reached by a private destination.
            ip daddr ${set privateV4} drop
            ip6 daddr ${set privateV6} drop
            ip daddr 0.0.0.0/0 accept
            ip6 daddr ::/0 accept''
    else if mode == "unrestricted" then
      ''
        # egress.mode = "unrestricted": the escape hatch. Everything the
            # host can reach, the prison can reach.
            ip daddr 0.0.0.0/0 accept
            ip6 daddr ::/0 accept''
    else throw "prison: unknown egress.mode ${mode} (expected none, targets, internet or unrestricted)";
in
pkgs.writeText "prison-ruleset.nft" ''
  # Generated by mkPrison. Loaded into the netns-owner container from the
  # host; unreachable and unmodifiable from inside the prison.
  table inet prison {
    chain input {
      type filter hook input priority filter; policy drop;
      iif "lo" accept
      ct state established,related accept
      ct state invalid drop
  ${optionalString (tcpListens != [ ]) (concatMapStringsSep "\n" (listenRule "tcp") tcpListens)}
  ${optionalString (udpListens != [ ]) (concatMapStringsSep "\n" (listenRule "udp") udpListens)}
    }

    chain output {
      type filter hook output priority filter; policy drop;
      oif "lo" accept
      ct state established,related accept
      ct state invalid drop
  ${egressBody}
    }

    # Nothing is routed through a prison.
    chain forward {
      type filter hook forward priority filter; policy drop;
    }
  }
''
